models:
  - name: dim_categories
    config:
      contract:
        enforced: true
    columns:
      - name: category_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: category_name
        data_type: varchar
      - name: description
        data_type: varchar
      - name: picture
        data_type: binary

  - name: dim_customers
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: varchar
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: customer_name
        data_type: varchar
      - name: contact_name
        data_type: varchar
      - name: contact_title
        data_type: varchar
      - name: address
        data_type: varchar
      - name: city
        data_type: varchar
      - name: region
        data_type: varchar
      - name: postal_code
        data_type: varchar
      - name: country
        data_type: varchar
      - name: phone
        data_type: varchar
      - name: fax
        data_type: varchar

  - name: dim_employees_territories
    config:
      contract:
        enforced: true
    columns:
      - name: employee_id
        data_type: integer
        description: not null
        constraints:
          - type: not_null
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: territory_id
        data_type: integer
        description: not null
        constraints:
          - type: not_null
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced

  - name: dim_employees
    config:
      contract:
        enforced: true
    columns:
      - name: employee_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: first_name
        data_type: varchar
      - name: last_name
        data_type: varchar
      - name: title
        data_type: varchar
      - name: title_of_courtesy
        data_type: varchar
      - name: birth_date
        data_type: date
      - name: hire_date
        data_type: date
      - name: address
        data_type: varchar
      - name: city
        data_type: varchar
      - name: region
        data_type: varchar
      - name: postal_code
        data_type: varchar
      - name: country
        data_type: varchar
      - name: home_phone
        data_type: varchar
      - name: extension
        data_type: varchar
      - name: photo
        data_type: binary
      - name: notes
        data_type: text
      - name: reports_to
        data_type: integer
      - name: photo_path
        data_type: varchar

  - name: fact_order_details
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: integer
        description: PK
        constraints:
          - type: not_null
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: product_id
        data_type: integer
        description: PK
        constraints:
          - type: not_null
      - name: unit_price
        data_type: numeric
      - name: quantity
        data_type: smallint
        description: not null
        constraints:
          - type: not_null
      - name: discount
        data_type: real

  - name: fact_orders
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: customer_id
        data_type: varchar
      - name: employee_id
        data_type: integer
      - name: order_date
        data_type: date
      - name: required_date
        data_type: date
      - name: shipped_date
        data_type: date
      - name: ship_via
        data_type: integer
      - name: freight
        data_type: numeric
      - name: ship_name
        data_type: varchar
      - name: ship_address
        data_type: varchar
      - name: ship_city
        data_type: varchar
      - name: ship_region
        data_type: varchar
      - name: ship_postal_code
        data_type: varchar
      - name: ship_country
        data_type: varchar
  
  - name: dim_products
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: product_name
        data_type: varchar
        description: not null
        constraints:
          - type: not_null
      - name: supplier_id
        data_type: integer
      - name: category_id
        data_type: integer
      - name: quantity_per_unit
        data_type: varchar
      - name: unit_price
        data_type: numeric
      - name: units_in_stock
        data_type: smallint
      - name: units_on_order
        data_type: smallint
      - name: reorder_level
        data_type: smallint
      - name: discontinued
        data_type: boolean
        description: not null
        constraints:
          - type: not_null

  - name: dim_regions
    config:
      contract:
        enforced: true
    columns:
      - name: region_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: region_description
        data_type: varchar
        description: not null
        constraints:
          - type: not_null

  - name: dim_shippers
    config:
      contract:
        enforced: true
    columns:
      - name: shipper_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: company_name
        data_type: varchar
        description: not null
        constraints:
          - type: not_null
      - name: phone
        data_type: varchar

  - name: dim_suppliers
    config:
      contract:
        enforced: true
    columns:
      - name: supplier_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: company_name
        data_type: varchar
        description: not null
        constraints:
          - type: not_null
      - name: contact_name
        data_type: varchar
      - name: contact_title
        data_type: varchar
      - name: address
        data_type: varchar
      - name: city
        data_type: varchar
      - name: region
        data_type: varchar
      - name: postal_code
        data_type: varchar
      - name: country
        data_type: varchar
      - name: phone
        data_type: varchar
      - name: fax
        data_type: varchar
      - name: homepage
        data_type: text

  - name: dim_territories
    config:
      contract:
        enforced: true
    columns:
      - name: territory_id
        data_type: integer
        description: PK
        constraints:
          - type: primary_key # not enforced  -- will warn & include
        tests:
          - unique            # need this test because primary_key constraint is not enforced
      - name: territory_description
        data_type: varchar
        description: not null
        constraints:
          - type: not_null
      - name: region_id
        data_type: integer
        description: not null
        constraints:
          - type: not_null